name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

<<<<<<< HEAD
permissions:
  contents: write

=======
>>>>>>> 9f5cc97eeefd678bc3e9c10e820b61277ea58807
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
<<<<<<< HEAD
          node-version: 20
=======
          node-version: 20  # 👈 changed from 18 to 20
>>>>>>> 9f5cc97eeefd678bc3e9c10e820b61277ea58807

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
